version: "3"
services:
  frontend:
    build: ./frontend
    container_name: 
    restart: unless-stopped
    ports:
     - 8000:8000
    links:
     - user
     - question

  user:
    build: ./backend/user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - 8001:8001
    links:
      - user-db

  question:
    build: ./backend/question-service
    container_name: question-service
    restart: unless-stopped
    ports:
      - 8002:8002
    links:
      - question-db

  user-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - 27017:27017
  
  question-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - 27017:27017