name: Deploy Function

on:
  push:
    branches:
      - serverless
      - master

jobs:
  deploy:
    name: Deploy Serverless
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: 'actions/checkout@v4'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}
    
     # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Grant Cloud Functions Permissions
      run: |
        gcloud projects add-iam-policy-binding ${{ secrets.GKE_PROJECT }} \
          --member=serviceAccount:${{ secrets.GKE_SA_KEY }} \
          --role=cloudfunctions.functions.sourceCodeSet
    
    - name: Deploy a Cloud Function
      id: deploy-function
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: fetchQuestions
        runtime: nodejs18
        project_id: ${{ secrets.GKE_PROJECT }}
        region: asia-southeast1