name: PeerPrep CI

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Build the service
      run: docker-compose up -d
  
  test:
    runs-on: ubuntu-latest
    name: Frontend Tests
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Frontend
      working-directory: ./frontend
      run: |
          npm install
          npm install -g @angular/cli
          xvfb-run -a ng test --watch=false --browsers=ChromeHeadless 
